# Push from officialbishowb/lb_planner repo to officialbishowb/test_repo repo
    

name: Auto Push
on:
  release:
    types: [published]
  push:
    branches: ['main', 'app','moodle']
  workflow_dispatch:

jobs:
  push-to-app-repo:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the src repo
          uses: actions/checkout@v3
          with:
            repository: officialbishowb/lb_planner
            path: src
            ref: app
          
        - name: Checkout the dest repo
          uses: actions/checkout@v3
          with:
            repository: officialbishowb/test_repo
            path: dest
            ref: main
            persist-credentials: false

        - name: Copy files from src to dest and add it so safe directory
          run: |
            cp -r src/* dest
            ls -l dest
            git config --global --add safe.directory dest/

        - name: Commit the changes
          run: |
            cd dest
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git commit -a -m "Auto Push from lb_planner"
        
        - name: Push the changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            repository: officialbishowb/test_repo
            branch: main
