# Push from officialbishowb/lb_planner repo to officialbishowb/test_repo repo
    

name: Auto Push
on:
  release:
    types: [published]
  push:
    branches: ['main', 'app','moodle']
  workflow_dispatch:


jobs:
  push-to-app-repo:

      runs-on: ubuntu-latest
      permissions:
        contents: write
        pull-requests: write
      steps:
        - name: Checkout the src repo
          uses: actions/checkout@v3
          with:
            repository: officialbishowb/lb_planner
            path: src
            ref: app
          
        - name: Checkout the dest repo
          uses: actions/checkout@v3
          with:
            repository: officialbishowb/test_repo
            path: dest
            ref: main
            persist-credentials: false
        - name: Copy files from src to dest and add it so safe directory
          run: |
            cp -r src/* dest
            git config --global --add safe.directory dest/
        - name: Add it to safe directory
          run: |
            cd dest
            git config --global --add safe.directory .

        - name: Commit the changes
          run: |
            cd dest
            git add .
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git commit -m "auto push from lb_planner"
        
        - name: Push the changes
          run: |
            cd dest
            ls -la
            
            

