# Push from officialbishowb/lb_planner repo to officialbishowb/test_repo repo
    

name: Auto Push
on:
  release:
    types: [published]
  push:
    branches: ['main', 'app','moodle']
  workflow_dispatch:


jobs:
  push-to-app-repo:

      runs-on: ubuntu-latest
      permissions:
        contents: write
        pull-requests: write
      steps:
        - name: Checkout the src repo
          uses: actions/checkout@v3
          with:
            repository: officialbishowb/lb_planner
            path: src
            ref: app
          
        - name: Checkout the dest repo
          uses: actions/checkout@v3
          with:
            repository: officialbishowb/test_repo
            path: dest
            ref: main
            persist-credentials: false

        - name: Copy files from src to dest and add it so safe directory
          run: |
            cp -r src/* dest
            git config --global --add safe.directory dest/

        - name: Commit and push files
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Auto Push from lbplanner"
            commit_options: "--no-verify"
            commit_user_name: "GitHub Actions"
            commit_user_email: "github-actions[bot]@users.noreply.github.com"
            repository: dest

