# Push lbplanner-app from lb_planner app branch

name: Push to organization repos
on:
  release:
    types: [published]
    branches: ['app']
  workflow_dispatch:
jobs:
  push-to-app-repo:
    name: Push to lbplanner-app repo from app branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy repository contents to temporary directory
      run: |
        mkdir -p /tmp/lb_planner
        cp -r . /tmp/lb_planner

    - name: Checkout lbplanner-app repo
      uses: actions/checkout@v2
      with:
        repository: officialbishowb/test_repo
        path: test_repo
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Copy repository contents to lbplanner-app repo
      run: |
        cp -r /tmp/lb_planner/. test_repo
    - name: Commit and push changes
      run: |
        cd test_repo
        git add .
        git commit -m "Update from lb_planner app branch"
        git push

    

