# Push lbplanner-app from lb_planner app branch

name: Push to organization repos
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
jobs:
  push-to-app-repo:
    name: Push to lbplanner-app repo from app branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: officialbishowb/lb_planner
        path: lb_planner
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: app

    - name: Copy repository contents to temporary directory
      run: |
        mkdir -p /tmp/
        cp -r . /tmp/
        ls -la /tmp/lb_planner

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: officialbishowb/test_repo
        path: test_repo
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Copy target repository contents to temporary directory
      run: |
        cp -r . /tmp/ 
        ls -la /tmp/test_repo

    - name: Copy files from source repository to target repository
      run: |
        cp -r /tmp/lb_planner/* /tmp/test_repo/
        ls -la /tmp/test_repo

    - name: Clean up by changing the origin and removing the old files except .git
      run: |
        cd /tmp/test_repo
        git remote set-url origin ${{ secrets.TARGET_REPO }}
        mv .git /tmp/
        rm -rf *
        mv /tmp/.git .

      
    - name: Commit and push changes
      run: |
        cd /tmp/test_repo
        git add .
        git config --global user.email "n/a"
        git config --global user.name "n/a"
        git commit -m "Push from lb_planner app branch"
        git push origin main

    


    

