# Push lbplanner-app from lb_planner app branch

name: Push to organization repos
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push-to-app-repo:
    name: Push to lbplanner-app repo from app branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: officialbishowb/lb_planner
        path: lb_planner
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: app

    - name: Copy repository contents to temporary directory
      run: |
        mkdir -p /tmp/
        cp -r . /tmp/
        ls -la /tmp/lb_planner

    

