# Push from officialbishowb/lb_planner repo to officialbishowb/test_repo repo
    

name: Auto Push
on:
  release:
    types: [published]
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  push-to-app-repo:
    name: Push to app repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: officialbishowb/test_repo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: app_repo
          ref: main
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          path: lb_planner
          ref: app
      - name: Copy files from source repo to target repo
        run: |
          cp -r lb_planner/* app_repo/
      - name: Commit files to target repo
        run: |
          cd app_repo
          ls -la
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update from lb_planner"
      - name: Push changes to target repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: officialbishowb/test_repo
          branch: main
          
      
          


